include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-rustdesk-discover
PKG_VERSION:=1.0
PKG_RELEASE:=2

PKG_LICENSE:=GPL-2.0-or-later

LUCI_DEPENDS:=+rustdesk-discoveryd +luci-base +rpcd +rpcd-mod-ucode

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
