#!/bin/sh /etc/rc.common
# Copyright (C) 2026
# RustDesk discovery daemon init script.

START=98
STOP=10

USE_PROCD=1

BIN=/usr/sbin/rustdesk-discoveryd
PROG=rustdesk-discoveryd
OUT_FILE=/tmp/rustdesk_peers.json

start_service() {
	procd_open_instance
	procd_set_param command "$BIN"
	procd_set_param pidfile /var/run/rustdesk-discoveryd.pid
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn 3600 5 5
	procd_close_instance
}

stop_service() {
	rm -f "$OUT_FILE"
}
